from typing import Any, Dict, Optional

from ..base import platform
from ..schemas import ExchangePrecision, Portfolio, Trades

class CoinSwitch:
    def __init__(self) -> None: ...
    def __set_signature_header(
        self,
        method: str,
        endpoint: str,
        payload: Dict[str, Any] = ...,
        params: Dict[str, Any] = ...,
    ) -> None: ...
    def ping(self) -> bool: ...
    def validate_keys(self) -> bool: ...
    def portfolio(self) -> Portfolio: ...
    def trades(self, exchange: platform, symbol: str) -> Trades: ...
    def exchange_precision(
        self, exchange: platform, symbol: Optional[str] = ...
    ) -> ExchangePrecision: ...
